Mi test
Navi-Cloud/Navi-App pull request #2
Opened 2021-10-02 20:03 UTC by mimwin

Test/ MyFileActivityTest, SearchActivityTest, MyFileFragmentTest 

Adding 'transaction' variable to MyFileActivity due to check whether fragment transaction is well in MyFileActivityTest

2021-10-10 12:19 UTC, KangDroid requested changes

2021-10-10 12:19 UTC, KangDroid commented on app/src/main/java/com/navi/file/view/activity/MyFileActivity.kt
> +            transaction = supportFragmentManager.beginTransaction().apply {
.

2021-11-19 20:15 UTC, mimwin commented on app/src/main/java/com/navi/file/view/activity/MyFileActivity.kt
> +            transaction = supportFragmentManager.beginTransaction().apply {
solved!

2021-11-20 12:34 UTC, KangDroid approved these changes

2021-11-20 12:35 UTC, merged